MedusaII/urls.py
#  Developed by Vinicius José Fritzen
#  Last Modified 20/04/19 08:49.
#  Copyright (c) 2019  Vinicius José Fritzen and Albert Angel Lanzarini

from django.views.defaults import server_error, page_not_found
from django.contrib import admin
from django.http import HttpResponseServerError
from django.urls import include, path

from MedusaII import settings

urlpatterns = \
    [
        path('admin/', admin.site.urls),
        path('accounts/', include('escola.urlsAuth')),
        # path('escola/', include('escola.urls')),
        path('', include('escola.urls')),
        path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
        path('', include('pwa.urls')),
        path('maintenance-mode/', include('maintenance_mode.urls')),
        path('markdownx/', include('markdownx.urls')),
        path('select2/', include('django_select2.urls')),
    ]
if settings.DEBUG:
    urlpatterns.append(path('500', server_error))
    urlpatterns.append(path('404', page_not_found))


handler500 = 'escola.views.handler500'

escola/urls.py
#  Developed by Vinicius José Fritzen
#  Last Modified 20/04/19 08:59.
#  Copyright (c) 2019  Vinicius José Fritzen and Albert Angel Lanzarini

from django.urls import include, path
from rest_framework import routers

import escola.views_aluno
import escola.views_cargo
import escola.views_conteudo
import escola.views_horario
import escola.views_materia
import escola.views_professor
import escola.views_tarefa
import escola.views_turma
from escola import api, views_profile, views_provas_marcadas
from escola.quotes.quotes_views import AllQuotesView
from escola.views_aviso import (AvisoDetailView, AvisoMixedCreateView,
                                AvisoTurmaCreateView)
from escola.views_feedback import FeedbackView

from . import views

router = routers.DefaultRouter()
router.register(r'users', api.UserViewSet)
router.register(r'groups', api.GroupViewSet)
router.register(r'profile', api.ProfileViewSet)
router.register(r'turma', api.TurmaViewSet)
router.register(r'seguidormanager', api.SeguidorManagerViewSet)
router.register(r'cargoturma', api.CargoTurmaViewSet)
router.register(r'professor', api.ProfessorViewSet)
router.register(r'materiadaturma', api.MateriaDaTurmaViewSet)
router.register(r'aluno', api.AlunoViewSet)
router.register(r'tarefa', api.TarefaViewSet)
router.register(r'tarefacompletacao', api.TarefaCompletacaoViewSet)
router.register(r'tarefacomentario', api.TarefaComentarioViewSet)
router.register(r'notificacao', api.NotificacaoViewSet)
router.register(r'horario', api.HorarioViewSet)
router.register(r'turno', api.TurnoViewSet)
router.register(r'turnoaula', api.TurnoAulaViewSet)
router.register(r'conteudo', api.ConteudoViewSet)
router.register(r'link_conteudo', api.LinkConteudoViewSet)
router.register(r'categoria_conteudo', api.CategoriaConteudoViewSet)

app_name = 'escola'

urlpatterns = [
    path('api/v1/', include(router.urls)),
    path('', views.index, name='index'),
    # turma
    path('turmas/', escola.views_turma.list_turmas, name='list-turmas'),
    path('turmas/add/', escola.views_turma.add_turma, name='add-turma'),
    path('turmas/<int:pk>', escola.views_turma.TurmaDetailView.as_view(), name='detail-turma'),
    path('turmas/<int:pk>/edit', escola.views_turma.edit_turma, name='edit-turma'),
    path('turmas/<int:pk>/delete', escola.views_turma.delete_turma, name='delete-turma'),
    path('alunos/populate/', escola.views_aluno.populate_alunos, name='populate-alunos'),
    # cargos
    path('turmas/<int:pk_turma>/cargos', escola.views_cargo.list_cargos, name='list-cargos'),
    path('turmas/<int:turma_pk>/cargos/add', escola.views_cargo.add_cargo, name='add-cargo'),
    path('turmas/cargos/edit/<int:pk>', escola.views_cargo.edit_cargo, name='edit-cargo'),
    path('turmas/cargos/delete/<int:pk>', escola.views_cargo.delete_cargo, name='delete-cargo'),
    # alunos
    path('turma/<int:turma_pk>/alunos', escola.views_aluno.list_alunos, name='list-alunos'),
    path('turma/<int:turma_pk>/alunos/add', escola.views_aluno.add_aluno, name='add-aluno'),
    path('turmas/aluno/<int:aluno_pk>/edit', views.edit_aluno, name='edit-aluno'),
    path('turmas/aluno/<int:aluno_pk>/delete', views.delete_aluno, name='delete-aluno'),
    # horario
    path('turma/<int:turma_pk>/horario', escola.views_horario.ver_horario, name='show-horario'),
    path('turma/<int:turma_pk>/horario/edit/<int:turno_cod>/<int:dia_cod>', escola.views_horario.alterar_horario,
         name='alterar-horario'),
    # professores
    path('professores/add', escola.views_professor.add_professor, name='add-professor'),
    path('professores/', escola.views_professor.list_professores, name='list-professores'),
    path('professor/<int:pk>/edit', escola.views_professor.edit_professor, name='edit-professor'),
    path('professor/<int:pk>/delete', escola.views_professor.delete_professor, name='delete-professor'),
    # materias
    path('turma/<int:turma_pk>/materias/add', escola.views_materia.add_materia, name='add-materia'),
    path('turma/<int:turma_pk>/materias', escola.views_materia.list_materias, name='list-materias'),
    path('materia/<int:materia_pk>/edit', escola.views_materia.edit_materia, name='edit-materia'),
    path('materia/<int:materia_pk>/delete', escola.views_materia.delete_materia,
         name='delete-materia'),
    path('materia/<int:pk>', escola.views_materia.MateriaDaTurmaDetailView.as_view(),
         name='detail-materia'),
    # tarefa
    path('turma/<int:turma_pk>/tarefas/add', escola.views_tarefa.add_tarefa, name='add-tarefa'),
    path('turma/<int:turma_pk>/tarefas', escola.views_tarefa.list_tarefa, name='list-tarefa'),
    path('turma/tarefa/<int:tarefa_pk>/edit', escola.views_tarefa.edit_tarefa, name='edit-tarefa'),
    path('turma/tarefa/<int:tarefa_pk>/delete', escola.views_tarefa.delete_tarefa, name='delete-tarefa'),
    path('turma/tarefa/<int:tarefa_pk>/concluir', escola.views_tarefa.concluir_tarefa, name='concluir-tarefa'),
    path('turma/tarefa/<int:tarefa_pk>', escola.views_tarefa.detalhes_tarefa, name='detalhes-tarefa'),
    # Seguir
    path('seguir/<int:pk>', views.seguir_manager, name='seguir'),
]

# Conteudos
urlpatterns += \
    [
        path('conteudo/<int:pk>',
             escola.views_conteudo.ConteudoDetail.as_view(),
             name='conteudo-detail'),
        path('conteudo/add/<int:pk_parent>',
             escola.views_conteudo.ConteudoCreate.as_view(),
             name='conteudo_add'),  # TODO: 13/04/2019 por wwwvi: Nomenclatura errada, mudar para add-conteudo
        path('conteudo/add/',
             escola.views_conteudo.ConteudoCreate.as_view(),
             name='conteudo_add'),  # TODO TAMBEM
        path('materia/<int:materia>/addConteudos',
             escola.views_conteudo.addConteudosAMateria.as_view(),
             name='add-conteudo-materia'),
        path('conteudo/<int:pk>/add', escola.views_conteudo.LinkConteudoCreateView.as_view(), name='add-link-conteudo'),
        path('link-conteudo/<int:pk>/remove', escola.views_conteudo.RemoveLinkFromConteudoView.as_view(), name='delete-link-conteudo'),
        path('conteudo/<int:pk>/add/<int:cat>', escola.views_conteudo.LinkConteudoCreateView.as_view(), name='add-link-conteudo'),
        path('conteudo/<int:pk>/edit', escola.views_conteudo.ConteudoUpdateView.as_view(), name='update-conteudo'),
        path('conteudo/<int:pk>/add-to-materias', escola.views_conteudo.AdicionarAVariasMateriasView.as_view(), name='adicionar-conteudo-a-varias-materias'),
    ]

# Notificações
urlpatterns += \
    [
        path('notificacoes', escola.views.NotificacaoListView.as_view(), name='notificacoes-list'),
        path('update-email', escola.views.atualisar_emails, name='update-email')
    ]

# Pagina de sobre
urlpatterns += \
    [
        path('sobre', escola.views.SobreView.as_view(), name='sobre'),
    ]

# Paginas do professor
urlpatterns += \
    [
        path('self/materias', escola.views_professor.MateriaProfessorListView.as_view(), name='materias_professor'),  # TODO: 13/04/2019 por wwwvi: Alterar name, nomeclatura esta errada
        path('self/conteudos', escola.views_conteudo.MeusConteudosListView.as_view(), name='conteudos-professor'),
    ]

# Offline template
urlpatterns += \
    [
        path('base_layout', escola.views.base_layout, name='base_layout_offline'),
    ]

# Perfil do usuario
urlpatterns +=\
    [
        path('self/emailChange', views_profile.email_change, name='self-email-change'),
    ]

# Marcar Provas

urlpatterns +=\
    [
        path('turmas/<int:turma_pk>/provas', views_provas_marcadas.ListaProvasTurmaView.as_view(),
             name='provas-turma-list'),
        path('provas/add/materia', views_provas_marcadas.CreateProvaMateriaView.as_view(),
             name='marcar-prova-materia'),
        path('provas/add/area', views_provas_marcadas.CreateProvaAreaView.as_view(),
             name='marcar-prova-area'),
        path('self/provas', views_provas_marcadas.ListaProvasProfessorView.as_view(),
             name='provas-professor'),  # As provas do professor
        path('provas/materia/<int:pk>/delete', views_provas_marcadas.ProvaMateriaDeleteView.as_view(),
             name='provas-materia-delete'),
        path('provas/area/<int:pk>/delete', views_provas_marcadas.ProvaAreaDeleteView.as_view(),
             name='provas-area-delete'),
        path('provas/<int:pk>', views_provas_marcadas.ProvaDetailView.as_view(),
             name='prova-detail'),
        path('turmas/<int:pk>/dias_livres', views_provas_marcadas.CalendarioTurmaDatasLivresView.as_view(),
             name='turma-provas-calendario'),
    ]

# Quotes

urlpatterns += \
    [
        path('all-quotes', AllQuotesView.as_view(), name='todas-quotes'),
    ]

# Feedback

urlpatterns += \
    [
        path('feedback', FeedbackView.as_view(), name='feedback'),
    ]

# Avisos

urlpatterns += \
    [
        path('aviso/add-turma',
             AvisoTurmaCreateView.as_view(),
             name='aviso-add-turma'),
             
        path('aviso/<int:pk>',
             AvisoDetailView.as_view(),
             name='aviso-detail'),

        path('aviso/add-mixed',
             AvisoMixedCreateView.as_view(),
             name='aviso-add-mixed')
    ]

# Temporarias

# urlpatterns += \
#     [
#           JAMAIS ADICIONAR NOVAMENTE, É DEBUG!!!
#         path('users/', escola.views.UserListView.as_view())
#     ]

escola/views.py
#  Developed by Vinicius José Fritzen
#  Last Modified 20/04/19 09:00.
#  Copyright (c) 2019  Vinicius José Fritzen and Albert Angel Lanzarini

import datetime
import logging

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render, render_to_response
from django.template import RequestContext
from django.views.generic import ListView, TemplateView

from escola.models import (Horario, Notificacao, Notificador, Turma, Turno,
                           TurnoAula)

from .decorators import *
from .forms import *
from .models import *
from users.models import Aluno

logger = logging.getLogger(__name__)


@is_user_escola
@login_required
def index(request):
    logger.info('views:index; user_id: %s', request.user.pk)
    context = {'request': request}

    logger.info('Antes de renderizar a view index, user: %s', request.user.pk)

    if request.user.profile_escola.is_aluno:
        logger.info('É um aluno renderizando tela do aluno')
        context.update({'turma': request.user.aluno.turma})
        return render(request, 'escola/home_aluno.html', context=context)

    if request.user.profile_escola.is_professor:
        logger.info('É um professor renderizando tela do professor')
        return render(request, 'escola/home_professor.html', context=context)
    logger.warning('O usuario não é nem professor nem aluno, renderizando a tela default')
    return render(request, 'escola/home_base.html', context=context)


@permission_required('escola.edit_aluno')
def edit_aluno():
    # TODO: Implement edit aluno
    raise NotImplementedError


@permission_required('escola.can_delete_aluno')
def delete_aluno(request, aluno_pk):
    aluno = get_object_or_404(Aluno, pk=aluno_pk)
    turma = aluno.turma
    aluno.delete()
    return HttpResponseRedirect(reverse('escola:list-alunos', args=[turma.pk]))


class SobreView(TemplateView):
    template_name = "escola/sobre.html"




@is_user_escola
@login_required
def seguir_manager(request, pk):
    seguidor = Notificador.objects.get(pk=pk)
    seguidor.adicionar_seguidor(request.user)
    return HttpResponseRedirect(request.GET.get('next', reverse('escola:index')))


class NotificacaoListView(LoginRequiredMixin, ListView):
    model = Notificacao
    template_name = "escola/notificacoes_list.html"
    context_object_name = 'notificacoes'

    def get_queryset(self):
        query = Notificacao.objects.filter(user=self.request.user).order_by('-dataCriado')
        self.request.user.profile_escola.read_all_notifications()
        return query


def handler404(request, exception, template_name="404.html"):
    response = render_to_response('404.html')
    response.status_code = 404
    return response


def handler500(request, template_name="500.html"):
    response = render_to_response('500.html', {'request': request})
    response.status_code = 500
    return response


def base_layout(request):
    template = 'escola/base.html'
    return render(request, template)


# class UserListView(ListView):
#     model = User
#     context_object_name = 'users'
#     template_name = 'listUser.html'


def atualisar_emails(request):
    Turma.atualizaProvas()
    Turma.atualizaTarefas()
    count = Notificacao.send_all_emails()
    return JsonResponse({'success': True, 'emails_sended': count})

escola/templates/escola/panels/link_conteudo.html
{%load markdown %}
{%if default%}
<li  class="list-group-item list-group-item-action">
    <div class="d-flex justify-content-between">
        <a href="{{link.link}}">
      <h5 class="mb-1">{{link.titulo}}
        {%for tag in link.tags.names%}
        <span class="badge badge-secondary">{{tag}}</span>
        {%endfor%}</h5></a>
        {% if can_remove%}
        <a href="{%url 'escola:delete-link-conteudo' link.pk%}" class="btn btn-danger" aria-label="Remover">
            <span aria-hidden="true">&times;</span>
        </a>
        {%endif%}
    </div>
    <p class="mb-1">{{link.descricao|md}}</p>
    <small>{{link.link}}</small>
</a>
{%endif%}

{%if youtube%}
<li class="list-group-item list-group-item-action">
    <div class="d-flex justify-content-between">
      <h5 class="mb-1">{{link.titulo}}
        {%for tag in link.tags.names%}
        <span class="badge badge-secondary">{{tag}}</span>
        {%endfor%}</h5>
        {% if can_remove%}
        <a href="{%url 'escola:delete-link-conteudo' link.pk%}" class="btn btn-danger" aria-label="Remover">
            <span aria-hidden="true">&times;</span>
        </a>
        {%endif%}
    </div>
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/{{y_id}}?rel=0" allowfullscreen></iframe>
    </div>
    <p class="mb-1">{{link.descricao|md}}</p>
</li>
{%endif%}

escola/templates/escola/panels/listaProvasMarcadas.html
<!--
  ~ Developed by Vinicius José Fritzen
  ~ Last Modified 22/05/19 14:42.
  ~ Copyright (c) 2019  Vinicius José Fritzen and Albert Angel Lanzarini
  -->

<div class="table-responsive">
  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th></th>
        <th>Título</th>
        <th>Data</th>
      </tr>
    </thead>
    {# Linhas #}
    <tbody>
    {% for prova in provas %}
      <tr>
        <td>{{prova.get_apresentacao}}</td>
        <td><a href="{{prova.get_absolute_url}}">{{prova.get_nome}}</a></td>
        <td>{{prova.get_data}}</td>
      </tr>
    {% endfor %}
    </tbody>

  </table>
</div>

escola/templates/escola/panels/listaTarefas.html
{% load sekizai_tags %}

{% for tarefa in tarefas %}

{% if comp and tarefa.1.completo %}
 <div class="tarefa-item card text-white bg-dark" id="tarefa-{{tarefa.0.pk}}"> <!--Dark-->
    <h5 class="card-header tarefa-materia text-success" id="tarefa-{{tarefa.0.pk}}-materia">{{tarefa.0.materia|title}}</h5>
    <div class="card-body">
        <h5 class="tarefa-titulo text-success" id="tarefa-{{tarefa.0.pk}}-titulo">
                <i class="fas fa-check" id="tarefa-{{tarefa.0.pk}}-titulo-check"></i>
                <i class="fas fa-exclamation-triangle" id="tarefa-{{tarefa.0.pk}}-titulo-warn" style="display: none"></i>
                {{tarefa.0.titulo|title}}</h5>
                <p>{{tarefa.0.descricao|truncatechars:236}}</p>
        <!--236 caracteres-->
        <div class="btn-group">
            <a href="{% url 'escola:detalhes-tarefa' tarefa.0.pk %}" class="btn btn-primary">Ver...</a>
            <a href="{% url 'escola:concluir-tarefa' tarefa.0.pk %}" class="btn btn-success tarefa-item-concluir-btn" id="tarefa-{{tarefa.0.pk}}-concluir-btn" data-id-tarefa="{{tarefa.0.id}}">
                <i class="fas fa-check" id="tarefa-{{tarefa.0.pk}}-concluir-btn-check"></i>
                <span  id="tarefa-{{tarefa.0.pk}}-concluir-btn-text">Concluido</span></a>
        </div>
    </div>
    <div class="card-footer text-muted">
        Até {{tarefa.0.deadline}}
    </div>
</div>
<br />
{% else %}
<div class="tarefa-item card text-white bg-dark" id="tarefa-{{tarefa.0.pk}}"> <!--Dark-->
<h5 class="card-header tarefa-materia" id="tarefa-{{tarefa.0.pk}}-materia">{{tarefa.0.materia|title}}</h5>
<div class="card-body">
    <h5 class="tarefa-titulo" id="tarefa-{{tarefa.0.pk}}-titulo">
            <i class="fas fa-check" id="tarefa-{{tarefa.0.pk}}-titulo-check" style="display: none"></i>
            <i class="fas fa-exclamation-triangle" id="tarefa-{{tarefa.0.pk}}-titulo-warn" style="display: none"></i>
            {{tarefa.0.titulo|title}}</h5>
    <p>{{tarefa.0.descricao|truncatechars:236}}</p>
    <!--236 caracteres-->
    <div class="btn-group">
        <a href="{% url 'escola:detalhes-tarefa' tarefa.0.pk %}" class="btn btn-primary">Ver...</a>
        {% if comp %}
        <a href="{% url 'escola:concluir-tarefa' tarefa.0.pk %}" class="btn btn-primary tarefa-item-concluir-btn" id="tarefa-{{tarefa.0.pk}}-concluir-btn" data-id-tarefa="{{tarefa.0.id}}">
            <i class="fas fa-check" style="display: none" id="tarefa-{{tarefa.0.pk}}-concluir-btn-check"></i>
            <span  id="tarefa-{{tarefa.0.pk}}-concluir-btn-text">Concluir</span></a>
        {% endif %}
    </div>
</div>
<div class="card-footer text-muted">
    Até {{tarefa.0.deadline}}
</div>
</div>
<br />
{% endif %}
{% endfor %}
{% addtoblock "js" %}
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
{% endaddtoblock %}
{% addtoblock "js" %}
        <script>
                function csrfSafeMethod(method) {
                    // these HTTP methods do not require CSRF protection
                    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
                }
                function bool_to_str(bool){
                    if(bool){
                        return 'Sim'
                    } else {
                        return 'Não'
                    }
                }
                function set_completacao_html(id, status){
                    if(status){
                        $('#tarefa-'+ id +'-materia').addClass("text-success")
                        $('#tarefa-'+ id +'-titulo').addClass("text-success")
                        $('#tarefa-'+ id +'-titulo-check').show()
                        $('#tarefa-'+ id +'-titulo-warn').hide()
                        $('#tarefa-'+ id +'-concluir-btn').addClass("btn-success")
                        $('#tarefa-'+ id +'-concluir-btn').removeClass("btn-primary")
                        $('#tarefa-'+ id +'-concluir-btn-check').show()
                        $('#tarefa-'+ id +'-concluir-btn-text').text('Concluido')
                    } else {
                        $('#tarefa-'+ id +'-materia').removeClass("text-success")
                        $('#tarefa-'+ id +'-titulo').removeClass("text-success")
                        $('#tarefa-'+ id +'-titulo-check').hide()

                        $('#tarefa-'+ id +'-concluir-btn').removeClass("btn-success")
                        $('#tarefa-'+ id +'-concluir-btn').addClass("btn-primary")
                        $('#tarefa-'+ id +'-concluir-btn-check').hide()
                        $('#tarefa-'+ id +'-concluir-btn-text').text('Concluir')
                    }
                }
                $('.tarefa-item-concluir-btn').on('click', function (event) {
                    event.preventDefault()
                    var csrftoken = Cookies.get('csrftoken');
                    var id_tarefa = $(this).attr('data-id-tarefa')
                    var url = "{% url 'escola:tarefa-set-as-finished' 1234561234%}".replace("1234561234", id_tarefa)
                    console.log(id_tarefa)
                    console.log(url)
                    $.ajax({
                        type: "POST",
                        headers:{  
                            "Accept":"application/json",//depends on your api
                            "Content-type":"application/x-www-form-urlencoded"//depends on your api
                        },
                        url: url,
                        beforeSend: function(xhr, settings) {
                            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                                xhr.setRequestHeader("X-CSRFToken", csrftoken);
                            }
                        },
                        success:function(response){
                            console.log(response);
                            r = response;
                            set_completacao_html(id_tarefa, r.concluido);
                        }
                      });
                  })
                </script>
{% endaddtoblock %}

escola/templates/escola/panels/panelQuote.html
<div class="container">
    <div class="shadow p-3 mb-5 bg-white rounded">
        <blockquote class="blockquote">
            <p class="mb-0">&ldquo;{{quote}}&rdquo;</p>
            <footer class="blockquote-footer">{{autor}}</footer>
        </blockquote>
    </div>
</div>

escola/templates/escola/panels/panelQuotesList.html
{%load panels%}
{%for id in quotes_ids%}

    {%panel_quote_esp id%}

{%endfor%}

escola/templates/escola/panels/resumoHojeProfessor.html
<!--  Context: turmas-hoje -->


<section id="section-resumo-professor">
  <h1>Resumo de Hoje({% now "SHORT_DATE_FORMAT" %})</h1>
  <div class="row">
    <!-- Turmas com aula no dia -->
    <div class="col-sm-2">
      <h5>Turmas</h5>
      <div class="btn-group-vertical" role="group">
        {% for mat in turmashoje %}
            <a href="{%url 'escola:detail-turma' mat.turma.id%}" class="btn btn-secondary">{{mat}}</a>
        {% endfor %}
      </div>
    </div>
    <div class="col-sm-4">
      <h5>Ferramentas</h5>
      <div class="btn-group-vertical" role="group">
          <!--<a href="{%url 'escola:aviso-add-turma' %}" class="btn btn-secondary">Enviar aviso turma</a>-->
          <a href="{%url 'escola:aviso-add-mixed' %}" class="btn btn-secondary">Enviar aviso</a>
          <a href="{%url 'escola:marcar-prova-materia' %}" class="btn btn-secondary">Marcar Prova</a>
      </div>
    </div>
    <!-- Provas -->
  </div>
</section>